spring:
   application:
     name: default-config
eureka:
  instance:
    prefer-ip-address: true  # The service will prefer its IP address for registration
  client:
    register-with-eureka: true  # Registers the service with Eureka
    fetch-registry: true  # Enables fetching of the Eureka registry
    service-url:
      defaultZone: http://localhost:8761/eureka/  # The Eureka server URL for registering services
